### ISSUE TITLE
nersuite.cpp:154:10: error: no member named 'set_bias' in 'CRFSuite::Tagger'

### ISSUE THREAD

**Issue by fnl** [nlplab/nersuite#23]
Got this error while trying to compile (`./configure && make` of the default  download) NERsuite 1.2.1 using CRFsuite 0.12 (and libLBFGS). A function called `CRFSuite::Tagger.set_bias(string)` doesn't seem to exist in either codebase (NER/CRFsuite). After commenting out line 154, the suite compiles.

**Comment by irifki** [comment]
Can you please tell us what you modified in autogen.sh and configure.in ? I'm having some issues similar to what you had but can seem to fix it!

**Comment by fnl** [comment]
As I didn't post the changes here, I assume there had been several issues. And I'm very sorry, but I long since have moved on and no longer have the files for that around. Overall, I guess you're better off opening a new issue with NERsuite here and asking Han-Cheol for help. Sorry I cannot give any better advice!
