### ISSUE TITLE
Segmentation Fault of nersuite tag

### ISSUE THREAD

**Issue by tholor** [nlplab/nersuite#35]
Hey, 
I am new to nersuite. I am following the steps from the[ "basic usage"](http://nersuite.nlplab.org/basic_usage.html) doc, but I am getting a "Segementation fault". The first two steps of the pipeline seem to work:
``` 
nersuite_tokenizer < test.txt > test.tok
nersuite_gtagger -d ~/nersuite/models/gtagger < test.tok > test.gtag 
Loading morphdic...done.
Loading pos_models................done.
Loading chunk_models....done.
``` 
The created file(s) look fine to me:
```
cat test.gtag
0	3	ZAP	ZAP	NN	B-NP
3	4	-	-	HYPH	I-NP
4	6	70	70	CD	I-NP
7	15	tyrosine	tyrosine	NN	I-NP
16	22	kinase	kinase	NN	I-NP
22	23	,	,	,	O
24	28	CD45	CD45	NN	B-NP
28	29	,	,	,	O
30	33	and	and	CC	O
34	35	T	T	NN	B-NP
36	40	cell	cell	NN	I-NP
41	49	receptor	receptor	NN	I-NP
50	61	involvement	involvement	NN	I-NP
62	64	in	in	IN	B-PP
65	67	UV	UV	NN	B-NP
67	68	-	-	HYPH	B-NP
69	72	and	and	CC	I-NP
73	77	H2O2	H2O2	NN	I-NP
77	78	-	-	HYPH	O
78	85	induced	induce	VBN	B-NP
86	87	T	T	NN	I-NP
88	92	cell	cell	NN	I-NP
93	99	signal	signal	NN	I-NP
100	112	transduction	transduction	NN	I-NP
112	113	.	.	.	O
```
 However the last step using `nersuite tag` fails

```
nersuite tag -m ~/nersuite/models/bc2gm/bc2gm.iob2.no_dic.m < test.gtag > test.ner

Segmentation fault (core dumped)
```

Any idea whats going wrong here?

**Comment by priancho** [comment]
Hi tholor,

Sorry for my late reply. I recently moved from Japan to South Korea and couldn't make time for debugging this problem.


The segfault error is from priancho/crfsuite.
When I updated crfsuite by syncing it with its original repo (chokkan/crfsuite), some codes related to label bias option were removed accidentally.
I made a bugfix and applied to priancho/crfsuite repo. 
Please try nersuite after re-installing nersuite with the new priancho/crfsuite.


Best wishes,
Hancheol

**Comment by tholor** [comment]
Hi Hancheol, 

thanks for the fix. Works like a charm now :+1: 

Best, 
Malte
